adobe/fetch

package.json
src/index.js
test/index.test.js

feat: expose fetch context to allow custom configuration

---

test/index.test.js

feat: option to force HTTP/1(.1) protocol

---

README.md
package-lock.json
package.json
src/index.js
test/index.test.js

feat: make cache size limit configurable

---

src/index.js
test/index.test.js

fix(index): sanitize method name

---

src/index.js
test/index.test.js

feat(index): support array-type query param values

---

src/index.js
test/index.test.js

fix: make sure returned Response is wrapped

---

src/index.js
test/index.test.js

fix: explicitly set Host header

---

README.md
src/index.js
src/response.js
test/index.test.js

Support AbortController for aborting fetch operations

---

.circleci/config.yml
.github/workflows/semver-check.yaml
README.md

feat: replace references to "master" branch with "main"

---

src/index.js
test/index.test.js

fix: follow redirects by default

---

README.md
package-lock.json
package.json
src/index.js
test/index.test.js

feat: support URLSearchParams and FormData as body

---

.circleci/config.yml
.github/workflows/semantic-release.yaml

https://github.com/adobe/helix-home/issues/166

chore: use gh action for release

---

src/index.js

fix(index): workaround for persistent ERR_HTTP2_INVALID_SESSION errors

---

src/fetch/headers.js
test/core/index.test.js
test/fetch/headers.test.js

coerce non-string header values to string

---

src/fetch/body.js
src/fetch/request.js
src/fetch/response.js
src/index.d.ts
test/fetch/response.test.js

feat(response): guess Response content-type

---

test/core/index.test.js
test/fetch/index.test.js

Test for JSON PATCH

---

.vscode/launch.json
src/fetch/body.js

fix(body): TypeError on errored stream

---

src/fetch/index.js
test/fetch/index.test.js

fix: don't manipulate location header

---

test/fetch/index.test.js

Regression: redirect=manual should not alter location header

---

package-lock.json
src/fetch/response.js
test/fetch/response.test.js

fix(response): don't set content-type for null body

---

test/core/index.test.js
test/fetch/index.http2.test.js

test: consistent cleanup

---

src/core/h1.js
src/core/h2.js
src/core/index.js
test/fetch/index.http1.test.js
test/fetch/index.http2.test.js

fix: concurrent h2 requests to same origin using separate contexts

---

src/core/request.js
test/core/index.test.js

use buffer.length for buffers.

feat(core): use buffer.length for content-length if possible

---

src/core/h1.js
src/index.d.ts

fix: properly propagate global rejectUnauthorized context option

---

src/core/h2.js
test/core/h2c.test.js
test/fetch/index.http2.test.js
test/fetch/index.test.js
test/fetch/redirect.test.js
test/fetch/resiliance.test.js
test/server.js

test: refactored test server and added resiliance tests

---

README.md
package-lock.json
src/fetch/abort.js
src/fetch/index.js
test/fetch/misc.test.js

feat: timeoutSignal can be canceled

---

package-lock.json
package.json

see https://nodejs.org/api/packages.html#packages_dual_commonjs_es_module_packages

fix: add distinct exports for commonjs and esm

---

src/core/request.js
test/fetch/resiliance.test.js

fix: handle server protocol h2->h1 downgrade

---

package.json

chore: npm keywords

---

package-lock.json
package.json

chore: dependency hygiene

---

package-lock.json
package.json

fix semantic release

---

src/api.d.ts

fix: DTS (issue #250)

---

src/fetch/index.js

fix(cache): don't allocate memory if cache is disabled

---

README.md
src/api.d.ts
src/common/utils.js
src/core/h1.js
src/core/h2.js
src/core/request.js
src/fetch/cacheableResponse.js
src/fetch/index.js
src/fetch/request.js
src/fetch/response.js
test/core/index.test.js
test/fetch/index.test.js
test/fetch/request.test.js

feat: decode option to disable automatic response body decoding

---

package-lock.json
package.json
src/core/request.js
src/fetch/body.js
src/fetch/request.js
test/common/utils.test.js
test/core/index.test.js
test/core/misc.test.js
test/fetch/index.test.js
test/fetch/request.test.js

fix: arrayBuffer request body

---

.circleci/config.yml

chore: bump circleci img

---

README.md
src/api.d.ts
src/fetch/body.js
src/fetch/headers.js
src/fetch/index.js
src/fetch/request.js
src/fetch/response.js
test/fetch/headers.test.js
test/fetch/index.test.js

fix: regression regarding Headers.plain(); introduced Headers.raw()

---

src/api.d.ts

fix(typings): export ALPNProtocol as "const enum"

---

src/core/request.js

https://github.com/webpack/webpack/issues/16724

fix: regression of PR #352

---

src/api.d.ts
src/fetch/errors.js

fix: TypeScript declarations

---

package-lock.json
test/core/h2c.test.js
test/core/index.test.js
test/fetch/index.http1.test.js
test/fetch/index.http2.test.js
test/fetch/index.test.js
test/fetch/redirect.test.js
test/fetch/resiliance.test.js
test/runServer.js
test/server.js

fix: flaky tests

---

package-lock.json
test/core/h2c.test.js
test/core/index.test.js
test/fetch/index.http1.test.js
test/fetch/index.http2.test.js
test/fetch/index.test.js
test/fetch/redirect.test.js
test/fetch/resiliance.test.js
test/runServer.js
test/server.js

test: use forked server

---

package-lock.json
package.json
src/fetch/cacheableResponse.js
test/core/index.test.js
test/core/misc.test.js
test/fetch/cache.test.js
test/fetch/index.http1.test.js
test/fetch/index.http2.test.js
test/fetch/index.test.js
test/fetch/misc.test.js
test/server.js
test/utils.js

test: replace flaky httpbin.org endpoint with own server

---

package-lock.json
src/common/utils.js
src/core/h1.js
src/core/h2.js
src/core/index.js
src/core/request.js
src/fetch/index.js

fix: debug namespace is "adobe/fetch"

---

src/core/request.js

Bypass alpn cache when alpn not negotiated

Bypass alpn cache when alpn not negotiated (#410)

---

.renovaterc.json
README.md
package-lock.json
package.json
src/core/request.js
src/fetch/index.js

chore: stick to v7 of lru-cache to avoid bloating package

---

.renovaterc.json
README.md
package-lock.json
package.json
src/core/request.js
src/fetch/index.js

chore: stick to lru-cache v7 to avoid bloating package

---

src/core/h2.js

https://github.com/adobe/fetch/issues/437

Allow passing settings object in adobe context h2 (#437)

---

src/fetch/index.js
test/fetch/index.test.js

https://github.com/adobe/fetch/issues/447

fix: redirect behaviour according to current fetch spec

---

src/core/request.js
src/fetch/index.js
src/index.d.ts
test/fetch/index.http1.test.js
test/fetch/resiliance.test.js

fix: disable h1 keep-alive by default

---

src/core/h1.js

fix: revert PR #476 due to potential regression

---

src/fetch/request.js
test/fetch/index.test.js

feat: support node built-in AbortController & AbortSignal
